### ISSUE TITLE
Switching backend to iptables and then reloading interrupts network

### ISSUE THREAD

**Issue by lonix1** [firewalld/firewalld#1129]
### What happened

I install and configure Firewalld during provisioning of a brand new Debian 11 VPS (using Ansible). One of the major changes I make is to switch to iptables.

After that, the network stops working. This is unexpected and I could'nt find mention of this in the docs.

### What you expected to happen

To be able to install and configure Firewalld, without network interruption.

### How to reproduce it (as minimally and precisely as possible)

- create a new debian 11 VPS, with a root password; start it
- log in as root, with the root password
- install and configure:
  ````sh
  $ apt update
  $ apt install firewalld -y

  $ firewall-cmd --state
  running

  $ sed -i -E "s/FirewallBackend=nftables/FirewallBackend=iptables/" /etc/firewalld/firewalld.conf

  $ firewall-cmd --add-interface=eth0 --permanent

  $ firewall-cmd --reload

  $ firewall-cmd --list-all
  public (active)
    target: default
    icmp-block-inversion: no
    interfaces: eth0
    sources:
    services: dhcpv6-client ssh
    ports:
    protocols:
    forward: no
    masquerade: no
    forward-ports:
    source-ports:
    icmp-blocks:
    rich rules:
  ````
- test:
  ````sh
  $ ping www.google.com
  ping: www.google.com: Temporary failure in name resolution
  ````

- interestingly, if I uninstall, the problem remains:
  ````sh
  $ sudo apt purge firewalld -y

  $ ping www.google.com
  ping: www.google.com: Temporary failure in name resolution
  ````

### Anything else we need to know?

I discovered it will work again after a reboot. However, this is an **automated provisioning process** (using ansible), so it introduces issues - it breaks the ansible play unless a reboot is done, and that itself is undesirable due to the way the process is run.

I've scoured the docs and tutorials without mention of this scenario.

### Firewalld Version

0.9.3

### Firewalld Backend

iptables

### Linux distribution

debian 11.7

### Linux kernel version

5.10.0-23-amd64

### Other information

Thank you.

**Comment by erig0** [comment]
There are plenty of other commands here. Does it reproduce without the switch to iptables?

**Comment by erig0** [comment]
> > Does it reproduce without the switch to iptables?
> 
> No. If I use it with nftables, then the network isn't interrupted after the `--reload`.

The optimization to [maintain existing connections](https://github.com/firewalld/firewalld/blob/35e2d2b5afa50861684a4f23126c219fb6301276/src/firewall/core/nftables.py#L444-L455) while firewalld is reloading is unique to the `nftables` backend. It can not be implemented in the `iptables` backend.

IMO, this can't be fixed for the iptables backend.

**Comment by erig0** [comment]
> What I don't understand is you mentioned "existing/established connections" - but what I observed:
> 
>     * the ssh connection from me to the server in an open terminal was preserved, but I couldn't make new connections to the server, and,
> 
>     * in that terminal window, I discovered the server's network was down ("Temporary failure in name resolution") so I couldn't even ping out

Oh. That's different than what I thought you were reporting.

Can you reproduce and share the output of `iptables-save` and `nft list ruleset` ?

**Comment by PizzaProgram** [comment]
Similar problem for me. 💥 

1. I had a perfectly nice working iptables config (ssh + webmin + wireguard) on Debian 11 latest.
2. Red here, that I should switch and install firewalld: https://wiki.debian.org/iptables
3. `apt install firewalld`

# 10 sec later I was locked out from my VPS completely !

- SSH terminal window disconnected, not even sure the install was finished as planned! 
  _(Because remote ssh terminal is terminating all running operations by default.)_
- Can not log back in since than!
- Only can see my virtual monitor of my VPS through QEMU (kvm8680), where:
    - is no copy-paste, 
    - impossible to type letters, like `=`.  _(except ALT + 061)_

![kép](https://github.com/firewalld/firewalld/assets/26026089/238ecd09-1208-430f-9bfd-bf15b46af6c1)

4. Quickly tried most obvious commands:
```
firewalld --disable
firewalld --stop

firewalld-cmd --disable
firewalld-cmd --stop
```
 - none recognised 👎 

5. Checked the [HowTo open port](https://firewalld.org/documentation/howto/open-a-port-or-service.html) in the doc, and tried:
```
firewall-cmd --permanent --zone=public --add-port=22/tcp
firewall-cmd --permanent --zone=public --add-port=10000/tcp
```
 - nothing changed.

6. Also found this page: https://firewalld.org/documentation/howto/enable-and-disable-firewalld.html
 - but there is not really any "Disable" section
So I've tried:
```
systemctl mask --now firewalld.service
systemctl disable --now firewalld.service
 ... got ignored
systemctl unmask --now firewalld.service
systemctl disable --now firewalld.service
 ... executed, but still can not log back in !
```

## And now ? 
 - spent already 2 hours trying to gain back control.
 - Do I have to wipe the whole system and loose 3 month of setup-work?

**Comment by PizzaProgram** [comment]
Also tried to uninstall / reinstall firewalld to maybe "fix it", but since it has activated some blocking, it can not download anything any more:

![kép](https://github.com/firewalld/firewalld/assets/26026089/3a6f0ffb-74b6-4ab1-b156-d80083c8aabd)

**Comment by PizzaProgram** [comment]
I was able to re-config the old iptables basics one by one by hand, and tried to re-install `firewalld` from QEMU, so I can see "the end".
Same result, stopped at 60% of the progress. (First it was 95% because the dependencies).

It seems like it is killing the network from under itself, so it can not finish installing anything.

![kép](https://github.com/firewalld/firewalld/assets/26026089/1efb9bcf-460c-4bbf-a55d-80febf9089d6)

_It's like dismounting the wings from the airplane you guys are flying on. 
Very "clever" concept... Thank you very much for all the lost hours (and hair)._

**Comment by erig0** [comment]
> Similar problem for me.

These are different problems. Yours appears to be related to your distribution and setup. In your case firewalld is not fully starting. Please open a new issue and check /var/log/firewalld for clues.

**Comment by erig0** [comment]
@lonix1, this is fixed. It will be in the next feature (or major) release.

**Comment by jgonyea** [comment]
I'm still seeing this issue on new Ubuntu 22.04 installations.  Like @lonix1 , I'm also limited to using iptables for the time being due to docker.  I'm experiencing the same behavior that I lose all network communication until a reboot is completed.

firewalld version : 1.1.1
iptables version: v1.8.7

![image](https://github.com/firewalld/firewalld/assets/1057441/3c1fea8b-7fe1-4391-9cf9-d2aaf47ef632)

**Comment by erig0** [comment]
This was fixed in v1.2.6, v1.3.3, v2.0.0. The fix was not backport to v1.1.z as that stream is no longer supported/developed.
