### ISSUE TITLE
direct passthrough removed permanently not runtime "removed" on reload/complete-reload

### ISSUE THREAD

**Issue by luizluca** [firewalld/firewalld#307]
I created a rule using

```
firewall-cmd --permanent --direct --add-passthrough ipv4 -A IN_public -m comment --comment test1
iptables -L IN_public | grep test1
(nothing as expected)
firewall-cmd --reload
iptables -L IN_public | grep test1
           all  --  anywhere             anywhere             /* test1 */
```

However, when I remove it, not --reload nor --complete-reload remove them from iptables

```
firewall-cmd --permanent --direct --remove-passthrough ipv4 -A IN_public -m comment --comment test1
iptables -L IN_public | grep test1
           all  --  anywhere             anywhere             /* test1 */
firewall-cmd --reload
iptables -L IN_public | grep test1
           all  --  anywhere             anywhere             /* test1 */
firewall-cmd --complete-reload
iptables -L IN_public | grep test1
           all  --  anywhere             anywhere             /* test1 */
systemctl restart firewalld
iptables -L IN_public | grep test1
(now it is gone)
```

The only operation that allowed me to remove it using only firewall-cmd is when it changes only runtime:

```
firewall-cmd --direct --remove-passthrough ipv4 -A IN_public -m comment --comment test1
```

Shouldn't reload do it?

**Comment by erig0** [comment]
firewalld attempts to save and restore direct rules when it performs a reload. It does this to support daemons that may add runtime direct rules (e.g. libvirt, fail2ban) - otherwise those daemons would have to actively monitor for a firewalld restart and reload their direct rules. It also does this for interface to zone assignments. IMO, this was a poor decision as it's very surprising for the user.

Before we considering changing this behavior we need to research why it was added in the first place.

As a workaround you can do a real daemon restart, e.g. `systemctl restart firewalld`.

The code in question:

https://github.com/firewalld/firewalld/blob/6a3ac5835e26980098b1226313984d667cd84918/src/firewall/core/fw.py#L959-L1003

**Comment by erig0** [comment]
This was actually fixed in v0.7.0. See #409 and the new FlushAllOnReload configuration option.

**Comment by DevDorrejo** [comment]
This issue is back.

cat /etc/os-release 
```
NAME="openSUSE Tumbleweed"
# VERSION="20220428"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20220428"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20220428"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed
```

firewall-cmd --version 
`1.1.1`

**Comment by erig0** [comment]
> This issue is back and need use systemctl restart firewalld.service.

The issue you reported in #959 is not the same issue.
